### PR TITLE
Disable close outside

### PR DESCRIPTION
**Pull request by Gildus**
To disable the closed out dialog (click outside) simply add the disableCloseOutside property to the value true

### CODE REVIEW

**Comment by qimingweng** [comment]
Seeing this makes me feel like the property should actually be called `dismissOnBackgroundClick` and defaults to true instead of the opposite, it's a little confusing when it's double negative.

**Comment by qimingweng** [comment]
Oh you know what, the better solution for this involves turning off the global click handler entirely, and simply adding a new click handler to the background... but that would seriously change the API, so this will have to do for now...

Actually I'm still kind of confused why the `!== this` works. Can you walk through that once...?

**Comment by cordoval** [comment]
@Gildus can you please do the change of the variable name to ```dismissOnBackgroundClick``` instead?

**Comment by Gildus** [comment]
Done

**Comment by Gildus** [comment]
@qimingweng I make a console.info with **target** and  **this.refs.self** and the result is:

target is the background all screen:
captura de pantalla de 2017-01-19 10-59-34

And the this.refs.self is:

captura de pantalla de 2017-01-19 11-00-39

In my case particular **target === this.refs.self** don't work for me, but the **target !== this.refs.self** 
According to the images and the console are always different

The unique condition **this.refs.self.contains(target)** is true.

**Comment by cordoval** [comment]
@qimingweng this is lingering and it is BC stable. Let's resolve 👍

**Comment by cordoval** [comment]
@qimingweng will you create a new minor release so we can use this or how to tell package.json to use this last sha1?

**Comment by qimingweng** [comment]
@cordoval Made a patch release, 4.0.5 I think

**Comment by qimingweng** [comment]
You can do ^4.0.5 in package.json, although ^4.0.0 would capture it as well

**Comment by cordoval** [comment]
it does not show here https://github.com/qimingweng/react-modal-dialog/releases

**Comment by cordoval** [comment]
nvm i see it https://www.npmjs.com/package/react-modal-dialog

so it was not needed the github release, great 👍 thanks!

**Comment by qimingweng** [comment]
Github releases are separate

**Comment by cordoval** [comment]
i was on version 2.0.0 i hope this jump is ok to 4.0.5!

**Pull request merged**
