### PR TITLE
fix for react 15.2.0 props warnings

### LINKED ISSUE #20: react 15.2.0 introduces prop warnings
Updating to react 15.2.0 brings along this **loud** warning in the console.

`warning.js?8a56:44 Warning: Unknown props 'componentIsLeaving', 'top', 'left', 'recenter' on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop`

### PR DESCRIPTION
**Pull request by rvanmil**
Resolves #20

### CODE REVIEW

**Comment by qimingweng** [comment]
@rvanmil I pass the other props along so you can send things down if you need. I already implement a `...rest`, do you know which key in particular is causing this issue?

**Comment by qimingweng** [comment]
If you add 

```
componentIsLeaving,
top,
left,
recenter,
```

To the props destructuring, this warning should also go away

**Comment by rvanmil** [comment]
Got it! I've updated the PR.

**Comment by CodeLuca** [comment]
merge please?

**Pull request merged**
