### PR TITLE
fix bug related to clicking outside of the modal

### PR DESCRIPTION
**Pull request by cordoval**

### CODE REVIEW

**Comment by qimingweng** [comment]
Can you explain this issue this solves in more detail? Happy to merge but not sure I get the problem

**Comment by qimingweng** [comment]
When you click on the this.refs.self ( target === this.refs.self ), you should not dismiss the dialog, so therefore shouldClickDismiss returns false. Am I missing something?

**Comment by qimingweng** [comment]
Oh, one other solution, by the way, is to set the onClose handler to be null. If there is no onClose, it does not go away.

If you want that to happen when there is a spinner, for example... that will do the trick.

**Comment by cordoval** [comment]
The problem with what you propose is that it will also dismiss the x closing circle which we don't want to do. What we want is only when someone clicks outside of the modal that this does not close immediately as if it were a cancel button.

The annoyance right now is that if you click on the container it closes it automatically. The container spreads the full width and this condition makes it close. If the target !== this.refs.self then it will evaluate into true and then it will avoid closing.

Try it and you will see what i mean.

**Comment by qimingweng** [comment]
Oh I see... I don't think I can approve this change. It's up to the user to determine whether or not clicking the background will dismiss the dialog. If you make it an option in ModalContainer or ModalBackground, I can buy that. But making this a global change would be a big breaking change.

**Comment by cordoval** [comment]
an option on ModalContainer then it will be, let me adapt it, unless you have a quick commit 👍 😊

**Comment by cordoval** [comment]
I need some help, the code that i see downloaded by npm under node_modules of this is very different from the one in this repository, can you please guide me as to how to develop the library under my node_modules so i can adapt the code further? appreciate in advance

**Comment by qimingweng** [comment]
Oh this is difficult to teach over github... have you used babel before?

**Comment by cordoval** [comment]
i have but it is always setup for me or i have set it up but lightly

**Comment by wujiang1900** [comment]
I think default behavior (most other implementation of Modal box) is to make the background not clickable, and you can only close the modal box to get back to the container.
What I'd suggest is to make background not clickable as the default, and provide an option to users who would like the opposite behavior (whatever we have it right now).
My 2 cents.
Thanks,

John Wu

**Comment by qimingweng** [comment]
It's not that simple - that would change the API dramatically. We can add it, but we'd need to change the major the version number before the default was changed.

**Comment by qimingweng** [comment]
@cordoval Try developing on the website subfolder? `npm install && npm start` should work there.

**Comment by Gildus** [comment]
I added a new property  disableCloseOutside (boolean) for ModalDialog https://github.com/qimingweng/react-modal-dialog/pull/43

For example:
```
<ModalDialog onClose={this.props.onClose} width={350} className="example-dialog" disableCloseOutside={true}>
        <h1>Second Dialog</h1>
        <p>When you hit esc, only this one will close</p>
      </ModalDialog>
```

**Comment by cordoval** [comment]
@qimingweng https://github.com/qimingweng/react-modal-dialog/pull/43 is good for you?

"ship is good, very good" ~ Fifield

Let's merge it if so, thanks 👍

**Comment by qimingweng** [comment]
@cordoval Let's continue the conversation on #43

**Pull request closed without merging**
