### PR TITLE
Toggle class on body when modal is opened/closed

### PR DESCRIPTION
**Pull request by vsubbotskyy**
To address this issue:
https://github.com/qimingweng/react-modal-dialog/issues/13
And maybe for some other scenarios when we need to tweak things outside of our modal.

Would be also great if you can update npm package.

### CODE REVIEW

**Comment by m1n0s** [comment]
@vsubbotskyy sorry if I'm wrong. 
I saw that you toggle class on `body`, but what about actual css that will disable scrolling? 
Is there any `overflow: hidden`?
Thanks.

**Comment by vsubbotskyy** [comment]
@m1n0s Technically you're absolutely right, I didn't include it in commit. But class on body gives you leverage to address it in your own css, i.e.:

```
.body.modal-dialog-opened {
  overflow-y: hidden;
}
```

Maybe somebody would like to do other stuff with the page when modal is active, it just gives you an easy way to do it with nested classes, e.g.:

```
.modal-dialog-opened .my-nested-element {
   /* your styles goes here */
}
```

**Comment by vsubbotskyy** [comment]
Seams like @qimingweng quietly ignored this PR anyway, like a couple of others. So I'm not sure if it will be easier to fork it and create your own npm package, or wait for author reaction.

**Comment by qimingweng** [comment]
@vsubbotskyy I apologize for the slow responses on everything - it's been extremely difficult to keep up with open source stuff in the last little while.

I have a suggestion, instead of specifically adding a class to the modal, we could instead have handlers (onModalOpen) and (onModalClose) and a user could choose to do any class manipulation there. Maybe even pass as an argument the new html target to the ModalOpen/ModalClose functions.

**Comment by m1n0s** [comment]
@qimingweng or it can be built-in feature (maybe under the flag) to avoid body scroll when modal opened because it is very common case.
And your suggestion above is very good as well.

**Comment by qimingweng** [comment]
@m1n0s I actually kinda liked that the body scrolled underneath the modal when I first built it...

I'm weary of adding too many specific features like this. I designed the system to be interchangeable so you could have any given combination of <ModalBackground> and <ModalDialog>... The most basic implementation would only use <ModalPortal>.

At work we have several different modal dialogs that are used with the same modal background.

**Comment by m1n0s** [comment]
@qimingweng you are the boss here :) And I agree with your idea.

**Comment by vsubbotskyy** [comment]
@qimingweng Thanks for the response and the suggestion! But help me understand your point. I suggested to toggle css class on _document.body_ (the root element, the one we append target element to). Adding the class to the modal itself doesn't serve the purpose because it's the `<body>` overflow we want to control. 
Correct me if I'm wrong, but seems like adding a class to the DOM element we modifying anyway isn't that bad idea (leaves a smallest possible footprint). And this is not specific feature, just a css class that doesn't change anything, just means to an end. With kind regards.

**Comment by qimingweng** [comment]
This a5fe27607057fa6759927900efbd9b77463de796 in version 4.0.2 should give you a handler to do your body class toggle.

The reason I don't want to specifically target the "body" is because it assumes too much about the environment and is unnecessarily performing an operation if somebody doesn't need them. It's not a particularly strong "practical" argument but more of a code neatness/ideological thing.

It's true that we already assume that there is a "document.body" since that's how the entire portal works. It just feels wrong for a portal to control a property about an object that technically encompasses it.

Anyway, now you can just put whatever function you want in that handler.

**Pull request closed without merging**
